config/routes.rb
Rails.application.routes.draw do

 get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
root :to => "users#new"
resources :users
resources :sessions
resources :search

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :email, :password, :password_confirmation

  before_save :encrypt_password
  has_secure_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  # def self.authenticate(email, password)
  #   user = find_by_email(email)
  #   if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  #     user
  #   else
  #     nil
  #   end
  # end

  # def encrypt_password
  #   if password.present?
  #     self.password_salt = BCrypt::Engine.generate_salt
  #     self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController


def index
end

def show
  end
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end


  def create
    $message= nil
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    $message= "Invalid email or password"
    redirect_to 'new'
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


def new
  @user = User.new
end


def show
 @user = User.find(params[:id])
end

def create
  @user = User.new user_params
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new"
  end
end

private

def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password
    )
  end

end

app/controllers/users_controllers.rb
class UsersController < ApplicationController


def @user = User.new
end


def show
@user = User.find(params[:id])
end

def create
  @user = User.new(params[:user])
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new"
  end
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<head>
  <title>layout one</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <link href="css/bootstrap-theme.min.css" rel="stylesheet">
  <link href="css/bootstrap.css" rel="stylesheet">
  <link rel="stylesheet" href="./one.css">
</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <!--
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>-->
      <a class="navbar-brand" href="#top">APP NAME</a>
    </div>
    <!--
    <div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
    <li><a href="#about">About</a></li>
    <li><a href="#contact">Contact</a></li>
  </ul>
</div>
-->

</div>
</nav>

<a name="top"></a>

<div class="container">
  <div class="jumbotron">

    <h2>Hi, Input...</h2>
    <p>height and spacing will be adjusted later</p>
    <br />
    <br />
    <br />
  </div>
</div>

<div class="row">
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="col-md-1"></div>
        <div class="col-md-10" id="form">
          <form method="" action="">
            <label>Search:</label>
            <input type="text" name="search_term" placeholder="what are you searching for?" id="field" required>
            &nbsp;
            <label>Safe search?</label>
            &nbsp;
            <input type="checkbox" name="safe_search">
            &nbsp;
            &nbsp;
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
              <i class="mdi-content-send right"></i>
            </button>
            <div class="col-md-1"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="container">
    <div class="videowrapper">
      <div id="player"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="container" id="columns">
    <div class="col-md-3">
      <h3>Watch</h3>
      <p><a href="">link 1</a></p>
      <p><a href="">link 2</a></p>
      <p><a href="">link 3</a></p>
    </div>
    <div class="col-md-3"><h3>Play</h3>
      <p><a href="">link 1</a></p>
      <p><a href="">link 2</a></p>
      <p><a href="">link 3</a></p>
    </div>
    <div class="col-md-3">
      <h3>Listen</h3>
      <p><a href="">link 1</a></p>
      <p><a href="">link 2</a></p>
      <p><a href="">link 3</a></p>
    </div>
    <div class="col-md-3">
      <h3>Learn</h3>
      <p><a href="">link 1</a></p>
      <p><a href="">link 2</a></p>
      <p><a href="">link 3</a></p>
    </div>
  </div>
</div>

<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement('script');

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player('player', {
    height: '390',
    width: '640',
    videoId: 'Ood3teygwh8',
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
}

// 4. The API will call this function when the video player is ready.
function onPlayerReady(event) {
  event.target.playVideo();
}

// 5. The API calls this function when the player's state changes.
//    The function indicates that when playing a video (state=1),
//    the player should play for six seconds and then stop.
var done = false;
function onPlayerStateChange(event) {
  if (event.data == YT.PlayerState.PLAYING && !done) {
    setTimeout(stopVideo, 6000);
    done = true;
  }
}
function stopVideo() {
  player.stopVideo();
}
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60928405-1', 'auto');
  ga('send', 'pageview');

</script>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Safe Search Engine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60928405-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/search/new.html.erb
<!--
<h1>Register:</h1>

<#%= form_for @user do |f| %>
  <#%= f.text_field :name %><br>
  <#%= f.label :email, "Email" %>:
  <#%= f.text_field :email %><br>
  <#%= f.label :password, "Password" %>:
  <#%= f.password_field :password %><br>
  <#%= f.submit %>
<#% end %>

 -->
<h1>Sign Up</h1>


<p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/new.html.erb
<h1>Register:</h1>

<%= form_for @user do |f| %>
  <%= f.label :name, "Name" %>:
  <%= f.text_field :name %><br>
  <%= f.label :email, "Email" %>:
  <%= f.text_field :email %><br>
  <%= f.label :password, "Password" %>:
  <%= f.password_field :password %><br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><% @user.name %></h1>
<br />
<h3><% @user.email %></h3>
<br />